version: "3"
services:
  samba:
    image: sheabot/daserver-samba:alpine
    container_name: daserver-samba
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139"
      - "445:445"
    restart: on-failure
    volumes:
      - ./smb.conf:/etc/samba/smb.conf:ro
      - ./private:/var/lib/samba/private
      - /mnt/raid:/mnt/raid
    tmpfs:
      - /var/lib/samba/private/msg.sock:mode=0700
