FROM sheabot/daserver-base:alpine

RUN apk add --update --no-cache \
        build-base \
        libffi-dev \
        openssh \
        openssl-dev \
        py3-paramiko \
        py3-psutil \
        py3-rarfile \
        python3 \
        python3-dev \
        rsync

COPY docker-entrypoint.sh /

ENTRYPOINT [ "/docker-entrypoint.sh" ]
