version: "3"
services:
  minidlna:
    image: sheabot/daserver-minidlna:alpine
    container_name: daserver-minidlna
    network_mode: host
    restart: on-failure
    volumes:
      - ./minidlna.conf:/etc/minidlna.conf:ro
      - /mnt/raid/data:/mnt/raid/data:ro
